### ISSUE TITLE
OS X 10.10 compiling issues

### ISSUE THREAD

**Issue by CandyFace** [hltj/wxMEdit#98]
Hi

I am having trouble compiling wxMEdit 2.9.9 on OS X 10.10, using wxWidgets 3.0.2 I have been able to get so far.. but atm. I am getting 'Processes.h' file not found.

If i am correct in assuming that is it looking for this header file?
/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/
HIServices.framework/Versions/A/Headers/Processes.h 
if so, then I get these 2 errors and 3 warnings.

src/mad_utils.cpp:199:32: warning: implicit conversion of NULL constant to
      'UInt32' (aka 'unsigned int') [-Wnull-conversion]
        procno.highLongOfPSN = NULL ;
                             ~ ^~~~
                               0
src/mad_utils.cpp:203:21: error: no member named 'processAppSpec' in
      'ProcessInfoRec'; did you mean 'processAppRef'?
        processinfo.processAppSpec = &fsSpec;
                    ^~~~~~~~~~~~~~
                    processAppRef
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:176:23: note: 
      'processAppRef' declared here
  FSRefPtr            processAppRef;
                      ^
src/mad_utils.cpp:203:36: error: assigning to 'FSRefPtr' (aka 'FSRef *') from
      incompatible type 'FSSpec *'
        processinfo.processAppSpec = &fsSpec;
                                   ^ ~~~~~~~
src/mad_utils.cpp:205:9: warning: 'GetProcessInformation' is deprecated: first
      deprecated in OS X 10.9 [-Wdeprecated-declarations]
        GetProcessInformation( &procno , &processinfo ) ;
        ^
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:513:1: note: 
      'GetProcessInformation' has been explicitly marked deprecated here
GetProcessInformation(
^
src/mad_utils.cpp:206:16: error: use of undeclared identifier
      'wxMacFSSpec2MacFilename'
        path = wxMacFSSpec2MacFilename(&fsSpec);
               ^
2 warnings and 3 errors generated.

It seems to be relate to my OS being 64 Bit and the function processAppSpec only being available on 32 bit.
I would appreciate some help

**Comment by CandyFace** [comment]
I have been able to get rid of the first two errors by forcing configure to make i386, but I am still having trouble with the undeclared identifier.

So far i Have been using this to create the makefile
CFLAGS="-arch i386" CXXFLAGS="-arch i386" LDFLAGS="-arch i386" ./configure --prefix=/usr/local/Cellar --with-wx-config=/usr/local/Cellar/wxmac/3.0.2/lib/wx/config/osx_cocoa-unicode-3.0 --with-icu=/usr/local/opt/icu4c

**Comment by hltj** [comment]
wxMac/wxWidgets-3 was not supported yet.
Please DO follow #57 to build with wxGTK-2.8.
